apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eunomia-operator
rules:
# needed by operator logic to manage the runners
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'  
# needed by operator logic when handling finalizers
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - list
# operator's resources  
- apiGroups:
  - eunomia.kohls.io
  resources:
  - '*'
  verbs:
  - '*'
